---
development:
  dialect: postgres
  database: front_study_api_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: front_study_api_development
  user: postgres
  password: postgres
  host: postgres
  pool: 5

production:
  dialect: postgres
  database: front_study_api_development
  user: postgres
  password: postgres
  host: postgres
  pool: 5
