version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ADDR=0.0.0.0
      - PORT=3000
      - GO_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_NAME=front_study_api_development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=front_study_api_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
